<script lang="ts">
	import { onMount } from 'svelte';
	import QRCode from 'qrcode';
	let token = $state(''); let user = $state<any>(null); let loading = $state(true); let error = $state(''); let notice = $state(''); let secret = $state(''); let otpauth = $state(''); let qr = $state(''); let code = $state(''); let password = $state(''); let disabling = $state(false);
	const api = async (path: string, init: RequestInit = {}) => { const headers = new Headers(init.headers); headers.set('content-type', 'application/json'); headers.set('authorization', `Bearer ${token}`); const r = await fetch(`/api/${path}`, {...init, headers}); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || 'Request failed'); return d; };
	onMount(async () => { token = localStorage.getItem('lbl-token') || ''; if (!token) { loading = false; return; } try { user = (await api('auth/me')).user; } catch { error = 'Sign in required.'; } loading = false; });
	async function setup() { error = ''; try { const d = await api('auth/totp/setup', {method:'POST'}); secret = d.secret; otpauth = d.otpauth; qr = await QRCode.toDataURL(otpauth, {width: 220, margin: 2}); notice = 'Scan the QR code, then enter the six-digit code to confirm.'; } catch (e) { error = e instanceof Error ? e.message : 'Unable to start TOTP setup'; } }
	async function enable() { error = ''; try { await api('auth/totp/enable', {method:'POST', body: JSON.stringify({code})}); user.totp_enabled = 1; notice = 'TOTP is enabled. Future sign-ins require your authenticator code.'; } catch (e) { error = e instanceof Error ? e.message : 'Invalid code'; } }
	async function disable() { error = ''; try { await api('auth/totp/disable', {method:'POST', body: JSON.stringify({code})}); user.totp_enabled = 0; secret = ''; otpauth = ''; qr = ''; disabling = false; code = ''; notice = 'TOTP is disabled.'; } catch (e) { error = e instanceof Error ? e.message : 'Invalid code'; } }
	async function resetPassword() { error = ''; try { await api('auth/password/reset', {method:'POST', body: JSON.stringify({password})}); password = ''; notice = 'Password updated.'; } catch (e) { error = e instanceof Error ? e.message : 'Unable to update password'; } }
</script>
<svelte:head><title>Security | BidLadders</title></svelte:head>
<div class="profile-shell"><nav class="detail-nav"><a class="brand" href="/"><img class="brand-logo" src="/bid.svg" alt="" /><span>BidLadders</span></a><a class="back-link" href="/">← Board</a></nav>
{#if loading}<div class="empty-state"><strong>Loading security...</strong></div>{:else if !user}<div class="empty-state"><strong>Sign in to manage security.</strong><a class="button dark" href="/">Return to BidLadders</a></div>{:else}<main class="profile-main"><header class="profile-heading"><div><p class="eyebrow">ACCOUNT SECURITY</p><h1>Protect your account.</h1><p>Manage authenticator access and your password.</p></div></header>
<section class="profile-section"><p class="eyebrow">AUTHENTICATOR APP</p>{#if user.totp_enabled}<strong>TOTP is enabled.</strong><p>Your authenticator code is required when signing in and changing your password.</p><button class="button ghost" onclick={() => disabling = true}>Disable TOTP</button>{:else}<p>Add an authenticator app with a QR code. Registration stays simple; you can enable this immediately after creating your account.</p>{#if !qr}<button class="button dark" onclick={setup}>Set up TOTP</button>{:else}<img class="totp-qr" src={qr} alt="Scan this QR code with your authenticator app" /><p>Manual key: <code>{secret}</code></p><div class="field"><label for="totp-enable">Authenticator code</label><input id="totp-enable" inputmode="numeric" maxlength="6" bind:value={code} /></div><button class="button dark" onclick={enable}>Enable TOTP</button>{/if}{/if}</section>
<section class="profile-section"><p class="eyebrow">PASSWORD</p><div class="field"><label for="password">New password</label><input id="password" type="password" bind:value={password} placeholder="12+ chars, upper/lower/number" /></div><p>Because you are already signed in, TOTP is not required for this password change.</p><button class="button dark" onclick={resetPassword}>Reset password</button></section>
{#if disabling}<section class="profile-section"><p>Enter a current authenticator code to disable TOTP.</p><div class="field"><label for="disable-code">Authenticator code</label><input id="disable-code" inputmode="numeric" maxlength="6" bind:value={code} /></div><button class="button coral" onclick={disable}>Confirm disable</button></section>{/if}{#if notice}<div class="notice">{notice}</div>{/if}{#if error}<div class="error-banner">{error}</div>{/if}</main>{/if}</div>
